language: java
before_install:
  # Install base Android SDK
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  - wget http://dl.google.com/android/android-sdk_r22.6.2-linux.tgz
  - tar xzf android-sdk_r22.6.2-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:$ANDROID_HOME/build-tools

  # install android build tools
  - wget https://dl-ssl.google.com/android/repository/build-tools_r19.0.3-linux.zip
  - unzip build-tools_r19.0.3-linux.zip -d $ANDROID_HOME
  - mkdir -p $ANDROID_HOME/build-tools/
  - mv $ANDROID_HOME/android-4.4.2 $ANDROID_HOME/build-tools/19.0.3


  # Maven 3.1.1
  #- wget http://www.us.apache.org/dist/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz
  #- tar xvf apache-maven-3.1.1-bin.tar.gz > /dev/null
  #- export MVN_HOME=`pwd`/apache-maven-3.1.1
  #- export PATH=${MVN_HOME}/bin/:${PATH}
  - mvn --version
  #Updates android sdk
  - echo y | android update sdk --filter platform-tools,android-19,addon-google_apis-google-19,extra-android-support,extra-android-m2repository --no-ui --force > /dev/null
  
  #support libraries
  - cd ..
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - git clone https://github.com/mosabua/maven-android-sdk-deployer.git
  - cd maven-android-sdk-deployer
  - mvn install -P 4.4
  - cd extras
  - mvn clean install -N
  - cd compatibility-v4
  - mvn clean install 
  - cd ../compatibility-v7-appcompat
  - mvn clean install
  - cd ../../..
  - cd mobilefood
  - pwd

install: mvn install -Dskip.unit.tests=true -Dskip.integration.tests=true -B -V

before_script:
- cd script
- npm install
- npm start &
- cd ..

script: mvn verify -B -Denvironment.is.travis  
